/**
 * Firebase Authentication Services
 *
 * This file handles:
 * - User registration
 * - User login
 * - User logout
 * - Firebase authentication initialization
 */

import {
  createUserWithEmailAndPassword,
  getAuth,
  signInWithEmailAndPassword,
  signOut
} from 'firebase/auth';

import app from './firebase-config';
import { createWithId } from './firebase-database';

/**
 * Initialize Firebase Authentication
 */
const auth = getAuth(app);

/**
 * Export authentication instance
 * Allows access to the current authenticated user
 */
export default auth;

/**
 * Register a new user
 *
 * @param email - User email address
 * @param password - User password
 * @param nickname - User nickname
 *
 * @returns Firebase authentication result
 */
export const signup = async (
  email: string,
  password: string,
  nickname: string
) => {

  // Create a new Firebase account
  const result = await createUserWithEmailAndPassword(
    auth,
    email,
    password
  );

  console.log(
    "./services/firebase-auth.ts - signup function",
    result
  );

  /**
   * Retrieve the unique user ID generated by Firebase
   */
  const uid = result?.user?.uid;

  /**
   * If the UID exists,
   * create a user document in the database
   */
  if (uid) {
    await createWithId("users", uid, {
      uid: uid,
      nickname: nickname
    });
  }

  return result;
};

/**
 * Log in an existing user
 *
 * IMPORTANT:
 * The function returns the Firebase promise.
 * This allows:
 * - await login(...) to correctly wait for authentication
 * - auth.currentUser to be available after login
 *
 * @param email - User email
 * @param password - User password
 *
 * @returns Firebase login result
 */
export const login = (
  email: string,
  password: string
) => {

  return signInWithEmailAndPassword(auth, email, password)

    /**
     * Login success
     */
    .then(function (result) {

      console.log(
        "./services/firebase-auth.ts - login function - SUCCESS",
        result
      );

      return result;
    })

    /**
     * Login error handling
     */
    .catch(function (error) {

      console.log(
        "./services/firebase-auth.ts - login function - ERROR : ",
        error.code
      );

      /**
       * Re-throw the error
       * so it can be handled in login.tsx
       */
      throw error;
    });
};

/**
 * Disconnect the current authenticated user
 *
 * @returns Firebase logout promise
 */
export const logout = () => {

  return signOut(auth).then(function () {

    console.log(
      "./services/firebase-auth.ts - logout function",
      "Déconnecté.e !"
    );
  });
};